#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v4
# autospec commit: f4bef72
#
Name     : R-cvTools
Version  : 0.3.3
Release  : 50
URL      : https://cran.r-project.org/src/contrib/cvTools_0.3.3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/cvTools_0.3.3.tar.gz
Summary  : Cross-Validation Tools for Regression Models
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-robustbase
BuildRequires : R-robustbase
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
cross-validation with minimal programming effort and assist
    users with model selection.

%prep
%setup -q -n cvTools
pushd ..
cp -a cvTools buildavx2
popd
pushd ..
cp -a cvTools buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710610954

%install
export SOURCE_DATE_EPOCH=1710610954
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/cvTools/DESCRIPTION
/usr/lib64/R/library/cvTools/INDEX
/usr/lib64/R/library/cvTools/Meta/Rd.rds
/usr/lib64/R/library/cvTools/Meta/features.rds
/usr/lib64/R/library/cvTools/Meta/hsearch.rds
/usr/lib64/R/library/cvTools/Meta/links.rds
/usr/lib64/R/library/cvTools/Meta/nsInfo.rds
/usr/lib64/R/library/cvTools/Meta/package.rds
/usr/lib64/R/library/cvTools/NAMESPACE
/usr/lib64/R/library/cvTools/NEWS
/usr/lib64/R/library/cvTools/R/cvTools
/usr/lib64/R/library/cvTools/R/cvTools.rdb
/usr/lib64/R/library/cvTools/R/cvTools.rdx
/usr/lib64/R/library/cvTools/doc/examples-full/example-aggregate-full.R
/usr/lib64/R/library/cvTools/doc/examples-full/example-bwplot-full.R
/usr/lib64/R/library/cvTools/doc/examples-full/example-cvSelect-full.R
/usr/lib64/R/library/cvTools/doc/examples-full/example-densityplot-full.R
/usr/lib64/R/library/cvTools/doc/examples-full/example-dotplot-full.R
/usr/lib64/R/library/cvTools/doc/examples-full/example-plot-full.R
/usr/lib64/R/library/cvTools/doc/examples-full/example-summary-full.R
/usr/lib64/R/library/cvTools/doc/examples-full/example-xyplot-full.R
/usr/lib64/R/library/cvTools/doc/examples/example-accessors.R
/usr/lib64/R/library/cvTools/doc/examples/example-aggregate.R
/usr/lib64/R/library/cvTools/doc/examples/example-bwplot.R
/usr/lib64/R/library/cvTools/doc/examples/example-cvFit.R
/usr/lib64/R/library/cvTools/doc/examples/example-cvReshape.R
/usr/lib64/R/library/cvTools/doc/examples/example-cvSelect.R
/usr/lib64/R/library/cvTools/doc/examples/example-cvTool.R
/usr/lib64/R/library/cvTools/doc/examples/example-cvTuning.R
/usr/lib64/R/library/cvTools/doc/examples/example-densityplot.R
/usr/lib64/R/library/cvTools/doc/examples/example-dotplot.R
/usr/lib64/R/library/cvTools/doc/examples/example-plot.R
/usr/lib64/R/library/cvTools/doc/examples/example-repCV.R
/usr/lib64/R/library/cvTools/doc/examples/example-subset.R
/usr/lib64/R/library/cvTools/doc/examples/example-summary.R
/usr/lib64/R/library/cvTools/doc/examples/example-xyplot.R
/usr/lib64/R/library/cvTools/help/AnIndex
/usr/lib64/R/library/cvTools/help/aliases.rds
/usr/lib64/R/library/cvTools/help/cvTools.rdb
/usr/lib64/R/library/cvTools/help/cvTools.rdx
/usr/lib64/R/library/cvTools/help/paths.rds
/usr/lib64/R/library/cvTools/html/00Index.html
/usr/lib64/R/library/cvTools/html/R.css
/usr/lib64/R/library/cvTools/tests/test-cvFit-once.R
/usr/lib64/R/library/cvTools/tests/test-cvFit-repeated.R
/usr/lib64/R/library/cvTools/tests/test-cvTool-once.R
/usr/lib64/R/library/cvTools/tests/test-cvTool-repeated.R
/usr/lib64/R/library/cvTools/tests/test-cvTuning-once.R
/usr/lib64/R/library/cvTools/tests/test-cvTuning-repeated.R
